name: Loan_prediction
channels:
  - defaults

dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.11.1
  - cloudpickle==3.0.0
  - numpy==1.25.2
  - packaging==23.1
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.11.2